# Определение токсичных комментариев

**Цель:** предупреждать участников чата о токсичных и оскорбительных комментариях, фильтровать комментарии с негативным содержимым

## Анализ датасета Toxic Russian Comments

Ссылка на датасет:
https://www.kaggle.com/datasets/alexandersemiletov/toxic-russian-comments/data

In [1]:
%pip install fg-data-profiling

Requirement already satisfied: fg-data-profiling in /usr/local/lib/python3.13/dist-packages (4.20.0)
Requirement already satisfied: scipy<1.19.0,>=1.8 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (2.2.3)
Requirement already satisfied: matplotlib<3.12,>=3.5 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (2.13.5)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (3.1.6)
Requirement already satisfied: visions<0.9,>=0.7.5 in /usr/local/lib/python3.13/dist-packages (from visions[type_geometry,type_image_path]<0.9,>=0.7.5->fg-data-profiling) (0.8.1)
Requirement already satisfied: numpy<2.6,>=1.22 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (2.1.3)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (0.15.0)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (1.9.2)
Requirement already satisfied: numba<0.68,>=0.60 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (0.61.2)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->fg-data-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->fg-data-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.5->fg-data-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.5->fg-data-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.5->fg-data-profiling) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.5->fg-data-profiling) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.5->fg-data-profiling) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.5->fg-data-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.5->fg-data-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba<0.68,>=0.60->fg-data-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2026.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.13/dist-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->fg-data-profiling) (2.46.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->fg-data-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.2.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.13/dist-packages (from visions<0.9,>=0.7.5->visions[type_geometry,type_image_path]<0.9,>=0.7.5->fg-data-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.13/dist-packages (from visions<0.9,>=0.7.5->visions[type_geometry,type_image_path]<0.9,>=0.7.5->fg-data-profiling) (3.6.1)
Requirement already satisfied: puremagic in /usr/local/lib/python3.13/dist-packages (from visions<0.9,>=0.7.5->visions[type_geometry,type_image_path]<0.9,>=0.7.5->fg-data-profiling) (2.2.0)
Requirement already satisfied: shapely in /usr/local/lib/python3.13/dist-packages (from visions[type_geometry,type_image_path]<0.9,>=0.7.5->fg-data-profiling) (2.1.2)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->fg-data-profiling) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->fg-data-profiling) (2.25.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->fg-data-profiling) (2.4.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=0.14.1->phik<0.13,>=0.12.5->fg-data-profiling) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib<3.12,>=3.5->fg-data-profiling) (1.17.0)

In [8]:
import pandas as pd
import numpy as np
import data_profiling
from data_profiling import ProfileReport
 # Для автоматического анализа данных

In [4]:
data_list = []
with open("/content/dataset.txt") as file:
    for line in file:
        labels = line.split()[0]
        text = line[len(labels)+1:].strip()
        labels = labels.split(",")
        mask = [1 if "__label__NORMAL" in labels else 0,
                1 if "__label__INSULT" in labels else 0,
                1 if "__label__THREAT" in labels else 0,
                1 if "__label__OBSCENITY" in labels else 0]
        data_list.append((text, *mask))

df = pd.DataFrame(data_list, columns=["text", "normal", "insult", "threat", "obscenity"])

print("Размер датасета:", df.shape)
df.head()

Размер датасета: (248290, 5)

,text,normal,insult,threat,obscenity
0,скотина! что сказать,0,1,0,0
1,я сегодня проезжала по рабочей и между домами ...,1,0,0,0
2,очередной лохотрон. зачем придумывать очередно...,1,0,0,0
3,"ретро дежавю ... сложно понять чужое сердце , ...",1,0,0,0
4,а когда мы статус агрогородка получили?,1,0,0,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248290 entries, 0 to 248289
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   text       248290 non-null  object
 1   normal     248290 non-null  int64
 2   insult     248290 non-null  int64
 3   threat     248290 non-null  int64
 4   obscenity  248290 non-null  int64
dtypes: int64(4), object(1)
memory usage: 9.5+ MB

In [9]:
# СОЗДАНИЕ ДЕТАЛЬНОГО ОТЧЕТА ПО ДАННЫМ С ПОМОЩЬЮ YDATA_PROFILING
profile = ProfileReport(df, title="Profiling Report")
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]
100%|██████████| 5/5 [00:12<00:00,  2.55s/it]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Датасет состоит из 248290 комментариев, все комментарии отнесены к одному из классов - normal, unsult, threat, obscenity. Разметка датасета качественная, пропусков нет.

По данным автоматического отчета можем сказать, что в датасете есть три проблемы:
- найдены дубликаты данных - необходимо удалить дубликаты строк перед обучением модели
- есть корреляция между классами - необходимо проанализировать и устранить причины, если возможно
- есть дисбаланс классов - необходимо сбалансировать классы перед обучением модели.

## Анализ датасета russian-inappropriate-messages

Ссылка на датасет:
https://www.kaggle.com/datasets/nigula/russianinappropriatemessages

In [10]:
df2 = pd.read_csv('/content/Inappapropriate_messages.csv')

print("Размер датасета:", df2.shape)
df2.head()

Размер датасета: (124597, 2)

                                                text  inappropriate
0  Бедный Ниссон, его бесконечных детей то похища...         0.9526
1  Все кто лишился девстенности после NUMBER - ом...         0.9972
2  Не знаю сам почему её туда отправили. Не торга...         0.0217
3  Проституция легальнаНелегальное предпринимател...         0.9986
4  Я бы повстречался с порноактрисой, только я не...         0.9998

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124597 entries, 0 to 124596
Data columns (total 2 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   text           124597 non-null  object
 1   inappropriate  124597 non-null  float64
dtypes: float64(1), object(1)
memory usage: 1.9+ MB

In [13]:
profile = ProfileReport(df2, title="Profiling Report")
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]
100%|██████████| 2/2 [00:07<00:00,  3.80s/it]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Датасет состоит из 124597 комментариев, каждый комментарий размечен по степени токсичности от 0 до 1. Разметка датасета качественная, пропусков нет, дубликатов нет.

Автоматический отчет не нашел проблем в данных. Однако при обучении модели стоит определить точку отсечения для попадания комментария в категорию "токсичный" и разметить датасет соответственно.